---
- name: Copy and tar /opt/myapp from node1 to ansible-1
  hosts: node1
  tasks:
    - name: Create backup directory on node1
      ansible.builtin.file:
        path: /backup
        state: directory

    - name: Copy /opt/myapp to backup
      fetch:
        src: /opt/myapp/
        dest: /backup//myapp_copy
        flat: yes
        
  
       

    
