---
- name: Copy and tar /opt/myapp from node1 to ansible-1
  hosts: node1
  tasks:
    - name: Create backup directory on node1
      community.general.archive:
        path: /opt/myapp
        dest: /backup/myapp.tart.gz
        format: gz

    - name: Copy /opt/myapp to backup
      fetch:
        src: /backup/myapp.tart.gz
        dest: /backup/myapp.tart.gz
        flat: yes
        
  
       

    
