---
- name: Copy and tar /opt/myapp from node1 to ansible-1
  hosts: all
  tasks:
    - name: Create backup tar file on node1
      archive:
        path: /opt/myapp
        dest: /backup/myapp.tar.gz
        format: gz

    - name: Copy /opt/myapp to backup
      copy:
        src: /backup/myapp.tar.gz
        dest: /home/student/backup
        remote_src: yes
        delegate_to: ansible-1

        
  
       

    
