---
- name: Backup files to remote server
  hosts: node1
  gather_facts: false

  vars:
    backup_dir: /backup
    local_dir: /opt/myapp
    remote_dir: /backup_remote
    remote_server: 3.145.125.231

  tasks:
    - name: Create backup directory if not exist
      file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Create local archive
      archive:
        path: "{{ local_dir }}"
        dest: "{{ backup_dir }}/myappbackup.tar.gz"
        format: gz


    - name: Copy archive to EE 
      fetch:
        src: "{{ backup_dir }}/myappbackup.tar.gz"
        dest: "{{ remote_dir }}/myappbackup.tar.gz"
        flat: yes
      
    - name: Copy archive from ee to remote server
      copy:
        src: "{{ remote_dir }}/myappbackup.tar.gz"
        dest: "/home/student/backup/myappbackup.tar.gz"
        remote_src: yes
      delegate_to: "{{ remote_server }}"
