---
- name: Copy and tar /opt/myapp from node1 to ansible-1
  hosts: all
  tasks:
    - name: Create backup tar file on node1
      archive:
        path: /opt/myapp
        dest: /backup/myapp.tart.gz
        format: gz

    - name: Copy /opt/myapp to backup
      fetch:
        src: /backup/myapp.tart.gz
        dest: /home/student/backup
        flat: yes
        
  
       

    
