---
- name: Find root users on Linux systems
  hosts: all
  become: true
  vars:
    output_file: "/var/log/findroot.log"

  tasks:
    - name: Find root users
      shell: 
        "cat /etc/passwd | awk -F: '$3 == 0 { print $1 }'"
      register: root_users
      changed_when: false
     
    - name: Debug root users
      debug:
        var: root_users.stdout_lines
 
    - name: Write root users to file
      copy:
        content: "{{ root_users.stdout }}"
        dest: "{{ output_file }}"
