---
- name: Restore files to remote server
  hosts: node1
  gather_facts: false

  vars:
    backup_dir: /backup
    local_dir: /opt/myapp1
    remote_dir: /backup_remote
    remote_server: ansible-1

  tasks:
    - name: Create restore directory if not exist
      file:
        path: "{{ local_dir }}"
        state: directory

    - name: Copy archive from ansible-1 to remote server
      fetch:
        src: /home/student/backup/myappbackup.tar.gz
        dest: "{{ local_dir }}"/myappbackup.tar.gz
        flat: yes
      delegate_to: "{{ remote_server }}"
